# All values in no of frames
BACKGROUND_COLOR: "#c6c3c6"
FRAME_RATE: 60

NO_TRAINING_TRIALS: 8
NO_BLOCKS: 7
NO_TRIALS_IN_BLOCK: 8

REACTION_KEYS: [ c, m, space ]
STIM_VER_ANGLE: 2.05
STIM_HOR_ANGLE: 2.15 #1.71
STIM_HOR_ANGLE_SHIFT: 0.30

PRE_STIM_TIME: 48
VARIABLE_TIME: 72
CUE_TIME: 3
CUE_TO_STIM_TIME: 3
STIM_TIME: 12
REACTION_TIME: 108

CUE_PROBABILITY: 0.5
INCORRECT_CUE_PROBABILITY: 0.15
CAR_SHIFT_PROBABILITY: 0.25
